# Generated by Django 5.0.3 on 2024-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Equipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogequipment",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
