# Generated by Django 5.0.2 on 2024-03-06 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BasicInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیمار ها',
            },
        ),
        migrations.CreateModel(
            name='PatientValuedSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.patient')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BasicInfo.catalogvaluedspecification')),
            ],
            options={
                'verbose_name': 'ویژگی بیمار',
                'verbose_name_plural': 'ویژگی های بیمار',
            },
        ),
    ]
