# Generated by Django 5.0.2 on 2024-03-07 20:12

import common.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("BasicInfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Personnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        validators=[common.validators.trim_string],
                        verbose_name="نام",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50,
                        validators=[common.validators.trim_string],
                        verbose_name="نام خانوادگی",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "مرد"), ("F", "زن")],
                        max_length=1,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="کد ملی"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=11, verbose_name="شماره تلفن همراه"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=250, null=True, verbose_name="آدرس"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="شماره کارت بانکی",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(null=True, verbose_name="تاریخ شروع همکاری"),
                ),
                (
                    "end_contract_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ پایان همکاری"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IDLE", "Ready"),
                            ("PRGS", "In progress"),
                            ("IACT", "In active"),
                        ],
                        default="IDLE",
                        max_length=4,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "last_status_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت آخرین وضعیت پرسنل"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت درباره پرسنل"
                    ),
                ),
                (
                    "areas",
                    models.ManyToManyField(
                        to="BasicInfo.catalogarea", verbose_name="محدوده ها"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="BasicInfo.catalogpersonnelrole",
                        verbose_name="نقش پرسنل",
                    ),
                ),
                (
                    "tag_specifications",
                    models.ManyToManyField(
                        to="BasicInfo.catalogtagspecification", verbose_name="تگ"
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسنل",
                "verbose_name_plural": "پرسنل",
            },
        ),
        migrations.CreateModel(
            name="PersonnelValuedSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=250, verbose_name="مقدار")),
                (
                    "personnel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Personnel.personnel",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="BasicInfo.catalogvaluedspecification",
                        verbose_name="ویژگی مقداری",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="personnel",
            name="valued_specifications",
            field=models.ManyToManyField(
                through="Personnel.PersonnelValuedSpecification",
                to="BasicInfo.catalogvaluedspecification",
                verbose_name="مهارت",
            ),
        ),
    ]
