# Generated by Django 5.0.3 on 2024-03-08 13:10

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Personnel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="national_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    common.validators.national_code,
                    common.validators.blacklist_national_codes,
                ],
                verbose_name="کد ملی",
            ),
        ),
    ]
