# Generated by Django 5.0.2 on 2024-03-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carecontract',
            name='personnel_payment_status',
        ),
    ]
