# Generated by Django 5.0.3 on 2024-03-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BasicInfo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogarea",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogcallreason",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogcallreferral",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogmedicalcenter",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogpersonnelrole",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogservice",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogtagspecification",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogtagspecificationcategory",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogvaluedspecification",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="catalogvaluedspecificationcategory",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="weekday",
            name="code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
