# Generated by Django 5.0.2 on 2024-03-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("BasicInfo", "0001_initial"),
        ("Customers", "0001_initial"),
        ("Orders", "0001_initial"),
        ("Personnel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call_type",
                    models.CharField(
                        choices=[("INC", "ورودی"), ("OUT", "خروجی")],
                        default="INC",
                        max_length=3,
                        verbose_name="ورودی یا خروجی",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ANS", "پاسخ داده شده"), ("REJ", "رد شده")],
                        default="ANS",
                        max_length=3,
                        verbose_name="وضعیت پاسخ",
                    ),
                ),
                (
                    "raw_phone_number",
                    models.CharField(
                        blank=True,
                        help_text="در صورتی که شماره در لیست مخاطبین وجود نداشت از این فیلد استفاده کنید",
                        max_length=11,
                        null=True,
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="برای جست جوی در شماره های تماس کارفرما از این فیلد استفاده کنید",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customers.client",
                        verbose_name="کارفرما",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Orders.carecontract",
                        verbose_name="قرارداد مربوطه",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Orders.order",
                        verbose_name="خدمت موردی مربوطه",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BasicInfo.catalogcallreason",
                        verbose_name="علت تماس",
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BasicInfo.catalogcallreferral",
                        verbose_name="معرف",
                    ),
                ),
            ],
            options={
                "verbose_name": "تماس کارفرما و دیگران",
                "verbose_name_plural": "تماس های کارفرما و دیگران",
            },
        ),
        migrations.CreateModel(
            name="PersonnelCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "call_type",
                    models.CharField(
                        choices=[("INC", "ورودی"), ("OUT", "خروجی")],
                        default="INC",
                        max_length=3,
                        verbose_name="ورودی یا خروجی",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ANS", "پاسخ داده شده"), ("REJ", "رد شده")],
                        default="ANS",
                        max_length=3,
                        verbose_name="وضعیت پاسخ",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Orders.carecontract",
                        verbose_name="قرارداد مربوطه",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Orders.order",
                        verbose_name="خدمت موردی مربوطه",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Personnel.personnel",
                        verbose_name="پرسنل",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BasicInfo.catalogcallreason",
                        verbose_name="علت تماس",
                    ),
                ),
            ],
            options={
                "verbose_name": "تماس پرسنل",
                "verbose_name_plural": "تماس های پرسنل",
            },
        ),
    ]
